In [1]:
import pandas as pd
import numpy as np


In [2]:
print(pd.__version__)


2.2.3


In [5]:
df = pd.read_csv(r'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
# dataframe shape
print(df.shape)

(9704, 11)


In [10]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [11]:
# checking for missing variables
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [16]:
df.fuel_efficiency_mpg.max() 

25.96722204888372

In [17]:
df.horsepower.median()

149.0

In [18]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [20]:
df_1 = df.fillna(0)

In [21]:
df_1.isnull().sum()

engine_displacement    0
num_cylinders          0
horsepower             0
vehicle_weight         0
acceleration           0
model_year             0
origin                 0
fuel_type              0
drivetrain             0
num_doors              0
fuel_efficiency_mpg    0
dtype: int64

In [22]:
df_1.horsepower.median()

146.0

In [29]:
df_2 = df_1[df_1['origin'] == 'Asia']

In [49]:
df_3 = df_2[['vehicle_weight','model_year']]

In [50]:
df_3 = df_3.head(7)

In [51]:
df_3

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [57]:
df_3['vehicle_weight'] = df['vehicle_weight'].astype(int)

In [58]:
df_3

vehicle_weight  model_year
8             2714        2016
12            2783        2010
14            3582        2007
20            2231        2011
21            2659        2016
34            2844        2014
38            3761        2019

In [59]:
x = df_3.to_numpy()

In [60]:
x

array([[2714, 2016],
       [2783, 2010],
       [3582, 2007],
       [2231, 2011],
       [2659, 2016],
       [2844, 2014],
       [3761, 2019]])

In [61]:
xT = x.transpose()

In [62]:
XTX = np.dot(xT,x)

In [63]:
XTX

array([[62222708, 41422688],
       [41422688, 28373339]])

In [64]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71732978e-07, -8.34682050e-07],
       [-8.34682050e-07,  1.25380993e-06]])

In [65]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [66]:
a = np.dot(XTX_inv,xT)

In [67]:
w = np.dot(a,y)

In [68]:
w

array([0.0138448, 0.5049392])

In [69]:
w.sum()

np.float64(0.5187840013008976)